name: u_til
version: 0.1.3
author: Axel Christ <adracus@gmail.com>
description: Several dart utilities which can be easily accessed with the $-function.
homepage: https://github.com/Adracus/u_til
documentation: https://github.com/Adracus/u_til
dev_dependencies:
  unittest: any
